// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEfuQY_Xtj5OcbzOmbTFpMte7RerOzzRM',
    appId: '1:548711261444:android:1a303cfaecfb8459729c51',
    messagingSenderId: '548711261444',
    projectId: 'maptilers-landmarks',
    storageBucket: 'maptilers-landmarks.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf7RQknCaEAOzXUao0hReh9I8huzXlOuU',
    appId: '1:548711261444:web:8166c471dfb40611729c51',
    messagingSenderId: '548711261444',
    projectId: 'maptilers-landmarks',
    authDomain: 'maptilers-landmarks.firebaseapp.com',
    storageBucket: 'maptilers-landmarks.firebasestorage.app',
    measurementId: 'G-1C2M11X68J',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf7RQknCaEAOzXUao0hReh9I8huzXlOuU',
    appId: '1:548711261444:web:027c139a02e31625729c51',
    messagingSenderId: '548711261444',
    projectId: 'maptilers-landmarks',
    authDomain: 'maptilers-landmarks.firebaseapp.com',
    storageBucket: 'maptilers-landmarks.firebasestorage.app',
    measurementId: 'G-WZJ3RTBV37',
  );

}